site_name: HSC FEU Configuration

nav:
  - Home: index.md

theme:
  name: material
  palette:
    primary: teal
  font:
    text: Roboto
  features:
    - navigation.indexes
    - navigation.sections
    - toc.integrate

plugins:
  - search
  - table-reader


markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: false
