[project]
name = "hscfeu-doc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-macros-plugin>=1.3.7",
    "mkdocs-material>=9.6.15",
    "mkdocs-table-reader-plugin>=3.1.0",
    "tabulate>=0.9.0",
]
